2025-05-29 01:18:45,850 - INFO - Initializing the system login
2025-05-29 01:18:47,374 - INFO - System login initialized!
2025-05-29 01:18:47,379 - INFO - Processing 50 questions in question type: scene_type
2025-05-29 01:18:47,379 - INFO - =============== Model answering question id: 39 (1/50) ===============
2025-05-29 01:18:47,380 - INFO - Question type: scene_type
2025-05-29 01:18:47,380 - INFO - Question: What is the primary natural feature shown in the image?
2025-05-29 01:18:47,380 - INFO - Question image path: /home/vol-llm/datasets/ISR/VRSBench/validation/Images_val/P0019_0003.png
2025-05-29 01:18:47,380 - INFO - Querying agent to answer the question
2025-05-29 01:18:47,970 - INFO - Receiving new event of type: metadata...
2025-05-29 01:18:47,970 - INFO - Event data:
{
  "run_id": "1f03c2ad-ee51-6c33-8483-e4f473927a85",
  "attempt": 1
}

2025-05-29 01:18:47,981 - INFO - Receiving new event of type: error...
2025-05-29 01:18:47,981 - INFO - Event data:
{
  "error": "Exception",
  "message": "Error during API call: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd250fd50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
}

